services:
  - type: web
    name: basqi-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        fromDatabase:
          name: basqi-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://basqi.netlify.app

databases:
  - name: basqi-mongodb
    plan: free
    region: ohio
    ipAllowList: []